name: jamil_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  get: ^4.7.3
  google_fonts: ^8.1.0
  flutter_screenutil: ^5.9.3
  pretty_qr_code: ^3.6.0
  flutter_svg: ^2.3.0
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  cloud_firestore: ^6.7.1
  firebase_storage: ^13.4.5
  image_picker: ^1.2.3
  image_cropper: ^12.2.1
  share_plus: ^12.0.0
  nfc_manager: ^4.0.2
  nfc_manager_ndef: ^1.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/backgrounds/
    - assets/icons/
    - assets/icons/nav/
    - assets/icons/settings/
    - assets/icons/social/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
    - family: ClashDisplay
      fonts:
        - asset: assets/fonts/ClashDisplay-Extralight.otf
          weight: 200
        - asset: assets/fonts/ClashDisplay-Light.otf
          weight: 300
        - asset: assets/fonts/ClashDisplay-Regular.otf
          weight: 400
        - asset: assets/fonts/ClashDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/ClashDisplay-Semibold.otf
          weight: 600
        - asset: assets/fonts/ClashDisplay-Bold.otf
          weight: 700